### ISSUE TITLE
Genome build

### ISSUE THREAD

**Issue by wdecoster** [HAShihab/fathmm-MKL#1]
Dear,

Looking forward to using this interesting tool. However, I was wondering which genome build was used to create the precomputed database? I expect 'unexpected' results when my variants of interest are from a different build than the dataset, e.g. hg19 vs hg38.

Kind regards,
Wouter De Coster

**Comment by HAShihab** [comment]
Hi Wouter,

That's a good point!  

FATHMM-MKL predictions are based on the GRCh37/hg19 genome build.  I have updated the README with this information.
